### ISSUE TITLE
Running code

### ISSUE THREAD

**Issue by cravisjan97** [tranleanh/haze-synthesize#3]
Hi! Thanks for releasing the code! I wanted to synthesize hazy images on some outdoor scene images. I first estimated depth from Monodepthv2. I then used your code to synthesize haze and I got a broadcasting error at `depth_img_3c[:,:,0] = depth_img`. Since my depth image has 3 channels already, I just initialized `depth_img_3c = depth_img`. But the results I got were not hazy images. They are as follows:

These are the input and depth map images(from Monodepthv2)
![Capture](https://user-images.githubusercontent.com/11577265/181861999-3b8d79b5-ccf7-428a-a2c4-c3d74ac5802a.PNG)
These are the transmission maps and hazy images for sparse (top row) and dense (bottom row)
![Capture](https://user-images.githubusercontent.com/11577265/181861191-46d32526-5b06-43ac-a255-59a08b751313.PNG)
These are synthesized haze images and not depth maps. I am not sure why this is the result. I would really appreciate it if you can help me with this

**Comment by tranleanh** [comment]
Hi,

I guess that the problem comes from the range of pixel values of your images.

For example, make sure that the depth image and the input image have the same pixel range from 0 to 255.

Good luck.

**Comment by cravisjan97** [comment]
Thanks for the response! The input and depth images are in the same pixel range (0-255). There is a depth normalizing code line (where the depth map is divided by 255) after the depth map loading code. Do you know what was the pixel range of your depth map from Monotype_v2? If possible can you share a sample depth map?
